// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noemdwhwothnturyglde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vZW1kd2h3b3RobnR1cnlnbGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDQ1NDUsImV4cCI6MjA2MTY4MDU0NX0.p9ST4nKcs0ho35wcMsmpfwH6JJMCHXzXzh4k7dTydwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);